spin_manifest_version = 2

[application]
name = "wasm-app"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "wasm-app"

[component.wasm-app]
# FIX: Point to the file in the root folder (where Docker puts it)
source = "wasm_app.wasm"
files = ["mobilenetv2.onnx"]

[component.wasm-app.build]
command = "cargo build --target wasm32-wasip1 --release"